# See docs folder for details on implementation

## Site Settings

### Site Information


### Site Structure

baseurl: "/poemjorge" # the subpath of your site
url: "https://elprieto.github.io/" # should not change for Recovery Hub projects

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
